export const hotelTypes=[
    "Budget",
    "Boutique",
    "Luxury",
    "Ski Resort",
    "Business",
    "Family",
    "Romantic",
    "Hiking Resort",
    "Cabin",
    "Beach Resort",
    "Golf Resort",
    "Motel",
    "All Inclusive",
    "Pet Friendly",
    "Self Catering",
];

export const hotelFacilities=[
    "Free Wi-Fi",
    "Free Parking",
    "Airport Shuttle",
    "Non-Smoking Rooms",
    "Restaurant",
    "Room Service",
    "Fitness Center",
    "Bar",
    "Breakfast",
    "Spa",
    "Swimming Pool",
    "Pet Friendly",
    "Family Rooms",
    "Disabled Guests",
    "Air Conditioning",
    "Private Beach",
    "Garden",
    "Terrace",
    "Ski Storage",
    "Ski-to-Door Access",
    "Sauna",
    "Hot Tub",
    "BBQ Facilities",
]